/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Handle push events
self.addEventListener('push', (event) => {
  let data = { title: 'SipWise', body: 'Time to check your BAC!' };
  
  if (event.data) {
    try {
      data = event.data.json();
    } catch (err) {
      data = { title: 'SipWise', body: event.data.text() };
    }
  }

  const options: any = {
    body: data.body,
    icon: '/sipwise/favicon.svg',
    badge: '/sipwise/favicon.svg',
    vibrate: [100, 50, 100],
    data: data,
  };

  event.waitUntil(
    self.registration.showNotification(data.title || 'SipWise', options)
  );
});

// Handle notification click events
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  // Focus or open the application
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      const scope = self.registration.scope;
      
      // Look for an open app window matching our scope
      for (const client of clientList) {
        if (client.url.startsWith(scope) && 'focus' in client) {
          return client.focus();
        }
      }
      
      // If no open window, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(scope);
      }
    })
  );
});
